"""
Configuration-driven domain definitions: anchors, keywords, regex patterns, intent verbs.

Anchors are embedded and averaged into per-domain prototype vectors at startup.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

from app.core.constants import DOMAIN_NAMES


@dataclass(frozen=True)
class DomainDefinition:
    """Single domain configuration."""

    name: str
    anchors: List[str]
    keywords: List[str]
    patterns: List[str]
    intent_verbs: List[str]
    phrase_boosts: List[str]


def _domains() -> Dict[str, DomainDefinition]:
    return {
        "coding": DomainDefinition(
            name="coding",
            anchors=[
                "Write a Python function that detects a cycle in a singly linked list "
                "using Floyd’s tortoise and hare; include edge cases for empty and length-1 lists.",
                "Debug this Java NullPointerException: the crash happens when lazy-loading "
                "a Hibernate association inside a parallelStream().",
                "Refactor this C++17 class to follow the rule of five; fix the double-free "
                "when copying objects that own raw pointers.",
                "Implement Dijkstra’s algorithm in JavaScript using a min-heap priority queue; "
                "handle disconnected components cleanly.",
                "Optimize this PostgreSQL query that filters JSONB with ->> and OR conditions; "
                "propose the right GIN index and explain tradeoffs.",
                "Design a RESTful API for idempotent order cancellation with ETags, "
                "conflict responses, and webhook retries.",
                "Add comprehensive pytest coverage for a Flask OAuth callback route, "
                "including token refresh and clock skew.",
                "Explain how to reverse a linked list iteratively versus recursively in "
                "Python and state time and space complexity.",
                "Convert this nested .then() promise chain in TypeScript to async/await with "
                "timeouts and AbortController cancellation.",
                "Implement a thread-safe bounded blocking queue in Java without "
                "java.util.concurrent classes, using wait/notify.",
                "Profile why this NumPy loop over rows is slow and vectorize it; compare "
                "memory layout for C versus Fortran order.",
                "Write a GitHub Actions workflow that caches pip, runs mypy and ruff, "
                "and fails if coverage drops below 85%.",
                "Sketch OpenAPI 3.1 for PATCH /users/{id} with partial updates, "
                "If-Match, and validation error schema.",
                "Given a leetcode-style constraint, implement two-sum with a hash map in "
                "Go and discuss collision handling.",
            ],
            keywords=[
                "python",
                "java",
                "javascript",
                "typescript",
                "c++",
                "cpp",
                "golang",
                "rust",
                "sql",
                "postgresql",
                "mysql",
                "leetcode",
                "dsa",
                "data structure",
                "algorithm",
                "function",
                "implement",
                "complexity",
                "big-o",
                "refactor",
                "debug",
                "stack trace",
                "unit test",
                "pytest",
                "jest",
                "graphql",
                "rest",
                "endpoint",
                "api",
                "async",
                "class",
                "method",
                "inheritance",
                "polymorphism",
                "object oriented",
                "oop",
                "interface",
                "kubernetes",
                "docker",
                "pandas",
                "numpy",
                "cycle",
                "detect",
            ],
            patterns=[
                r"\bdef\s+\w+\s*\(",
                r"\b(class|interface|enum|struct)\s+\w+",
                r"\b(import|from|package|using)\s+",
                r"\b(return|void|const|let|var)\b",
                r"\b```",
                r"\bSELECT\b.+\bFROM\b",
                r"\bINSERT\b|\bUPDATE\b|\bDELETE\b|\bWHERE\b",
                r"\bhttps?://",
                r"\.(py|js|ts|tsx|jsx|java|cpp|go|rs)\b",
                r"\bO\([^\)]+\)",
                r"\b(BFS|DFS|DP|DSA|JSON|YAML|REST|CRUD)\b",
                r"\blinked list\b",
                r"\bbinary tree\b",
                r"\b(hash map|hash table|hashmap)\b",
                r"\b(stack|queue|heap|trie)\b",
                r"\btime complexity\b|\bspace complexity\b",
            ],
            intent_verbs=[
                "implement",
                "write",
                "code",
                "debug",
                "refactor",
                "optimize",
                "generate",
                "fix",
                "deploy",
                "containerize",
                "profile",
                "test",
            ],
            phrase_boosts=[
                "write a function",
                "write a python function",
                "implement in python",
                "implement a",
                "debug this code",
                "linked list",
                "binary tree",
                "graph traversal",
                "dynamic programming",
                "sql query",
                "api endpoint",
                "time complexity",
                "rest api",
                "unit test",
                "hash map",
                "recursive solution",
            ],
        ),
        "math": DomainDefinition(
            name="math",
            anchors=[
                "Solve this integral step by step: ∫ x*exp(-x^2) dx using substitution.",
                "Prove by induction that 1^3 + … + n^3 = (n(n+1)/2)^2 for all positive integers n.",
                "Derive the quadratic formula from ax^2 + bx + c = 0 by completing the square.",
                "Compute eigenvalues and eigenvectors of the 2×2 matrix [[2,1],[1,2]].",
                "A fair coin is flipped until two heads in a row; find the expected number of flips.",
                "Minimize x^2 + y^2 subject to x + y = 1 using Lagrange multipliers.",
                "Solve this word problem: two trains approach at different speeds; when do they meet?",
                "Show √2 is irrational using proof by contradiction.",
                "Differentiate ln(x^2 + 1) / (x + 3) with respect to x using quotient and chain rules.",
                "Set up recurrence a_n = 2 a_{n-1} + n with a_0 = 1 and solve the closed form.",
                "Evaluate the limit as x→0 of sin(3x) / x without L’Hôpital, using known limits.",
                "Find all real solutions to sin(2x) = cos(x) on [0, 2π].",
                "In probability: if X ~ Bin(n,p), derive Var(X) and state when the normal approximates well.",
                "Approximate ln(1.05) with a second-order Taylor polynomial about x=0 and bound the error.",
            ],
            keywords=[
                "integral",
                "integrate",
                "derivative",
                "differentiate",
                "limit",
                "proof",
                "prove",
                "theorem",
                "lemma",
                "solve",
                "equation",
                "matrix",
                "eigenvalue",
                "eigenvector",
                "probability",
                "distribution",
                "expectation",
                "variance",
                "recurrence",
                "induction",
                "contradiction",
                "taylor",
                "series",
                "calculus",
                "algebra",
                "trigonometry",
                "optimization",
                "lagrange",
                "word problem",
            ],
            patterns=[
                r"\b∫",
                r"\bintegral\b",
                r"\bderivative\b|\bdifferentiate\b",
                r"\\int\b|\\frac\{",
                r"\$\$[\s\S]+?\$\$",
                r"\$[^$]+\$",
                r"\bprove\b|\bproof\b",
                r"\bby induction\b",
                r"\beigenvalue",
                r"\bP\([^)]+\)|\bE\[[^\]]+\]",
                r"\b\d+\s*/\s*\d+\b.*\b(probability|expectation)\b",
                r"\blimit\b.*\b(as|approaches)\b",
                r"\bsin\(|cos\(|tan\(",
            ],
            intent_verbs=[
                "solve",
                "prove",
                "derive",
                "calculate",
                "compute",
                "evaluate",
                "integrate",
                "differentiate",
                "minimize",
                "maximize",
                "simplify",
            ],
            phrase_boosts=[
                "solve this integral",
                "step by step",
                "differentiate this",
                "prove that",
                "probability distribution",
                "recurrence relation",
                "eigenvalues of matrix",
                "solve this equation",
                "by induction",
                "word problem",
                "definite integral",
                "partial derivative",
                "taylor series",
            ],
        ),
        "reasoning": DomainDefinition(
            name="reasoning",
            anchors=[
                "Compare microservices versus a modular monolith for eight engineers shipping weekly; "
                "what breaks first at scale?",
                "What are the tradeoffs between BFS and DFS on large sparse graphs for path finding?",
                "Justify choosing eventual consistency over strong consistency for a high-write social feed.",
                "Analyze edge cases if you compare floating-point sums versus decimal arithmetic in billing.",
                "Which cache eviction policy reduces tail latency for skewed key access, and why?",
                "Decide between synchronous and asynchronous replication for a regional outage scenario; "
                "walk through failure modes.",
                "Contrast optimistic versus pessimistic concurrency for checkout carts with contested inventory.",
                "When do extra indexes hurt OLTP throughput, and how would you measure it before/after?",
                "Explain why naive user_id hash sharding can create hot shards and how to mitigate.",
                "Evaluate zero-trust segmentation versus VPN-only access for contractors on architecture grounds.",
                "What assumptions break if leader election flakes during a network partition?",
                "Compare breadth-first versus depth-first exploration for dependency resolution in builds.",
                "Reason about CAP: for a bank ledger, which property would you relax last and why?",
                "Analyze the design of a rate limiter: token bucket versus sliding window under bursty traffic.",
            ],
            keywords=[
                "compare",
                "contrast",
                "tradeoff",
                "trade-off",
                "justify",
                "analysis",
                "analyze",
                "decide",
                "decision",
                "evaluate",
                "reasoning",
                "edge case",
                "failure mode",
                "architecture",
                "scalability",
                "latency",
                "throughput",
                "consistency",
                "availability",
                "partition",
                "assumption",
                "implication",
                "risk",
                "which is better",
                "versus",
                "vs",
            ],
            patterns=[
                r"\bcompare\b.*\b(vs\.?|versus|and)\b",
                r"\btrade-?offs?\b|\btradeoffs\b",
                r"\bwhat are the (tradeoffs?|risks?)\b",
                r"\bjustify\b|\banalyze the design\b",
                r"\bwhich (one |option |approach )?is better\b",
                r"\bedge cases?\b",
                r"\bfailure modes?\b",
                r"\bpros and cons\b",
                r"\brainstorm\b.*\b(options|approaches)\b",
            ],
            intent_verbs=[
                "compare",
                "justify",
                "analyze",
                "decide",
                "reason",
                "evaluate",
                "assess",
                "contrast",
            ],
            phrase_boosts=[
                "compare and contrast",
                "what are the tradeoffs",
                "justify your answer",
                "edge cases",
                "which is better",
                "analyze the design",
                "failure modes",
                "versus",
                "trade-offs",
                "root cause",
                "decision criteria",
                "under what assumptions",
            ],
        ),
        "summarization": DomainDefinition(
            name="summarization",
            anchors=[
                "Summarize this 2,000-word article into five crisp bullets for executives.",
                "Give a tight TL;DR of this earnings call focusing on guidance changes only.",
                "Condense this literature review to a one-page memo with citation placeholders.",
                "Produce a recap of this talk: main claim, three supporting ideas, one caveat.",
                "Turn this long Slack thread into a short decision log with owners and open questions.",
                "Summarize the methods and results of this paper without long verbatim quotes.",
                "Provide an executive summary of this policy document with risks highlighted.",
                "Boil this strategy deck to three takeaways and one KPI to watch.",
                "Give a neutral summary of both sides of this debate without loaded language.",
                "Reduce this RFC to a five-sentence overview a PM can skim in one minute.",
                "Summarize the plot for a reading group, spoiler-free until the halfway mark.",
                "Compress this multi-day workshop agenda into time-boxed themes only.",
                "Abstract the patient handoff note into action items only (fictional scenario).",
                "High-level summary of this technical design: goals, non-goals, and open questions.",
            ],
            keywords=[
                "summarize",
                "summary",
                "tl;dr",
                "tldr",
                "condense",
                "compress",
                "abstract",
                "recap",
                "overview",
                "executive summary",
                "in short",
                "bullet points",
                "key points",
                "high-level",
                "digest",
                "outline",
                "minutes",
                "highlights",
                "abbreviate",
                "shorter",
            ],
            patterns=[
                r"\bsummar(y|ize|ise)\b",
                r"\btl;?dr\b",
                r"\bin (a few|two|three|five) (sentences|bullet|bullets)\b",
                r"\bexecutive summary\b",
                r"\bkey takeaways\b",
                r"\bhigh-?level overview\b",
                r"\bshort summary\b",
                r"\bcondense this\b",
            ],
            intent_verbs=[
                "summarize",
                "condense",
                "compress",
                "recap",
                "shorten",
                "abbreviate",
            ],
            phrase_boosts=[
                "summarize this",
                "tl;dr",
                "in 5 bullet points",
                "short summary",
                "condense this",
                "executive summary",
                "key takeaways",
                "high-level summary",
                "in a few sentences",
                "give me the gist",
            ],
        ),
        "extraction": DomainDefinition(
            name="extraction",
            anchors=[
                "Extract all invoice line items as JSON with sku, qty, unit_price_cents, tax_code.",
                "Pull out every date in this email thread and normalize to ISO-8601.",
                "From this paragraph list each company name and ticker symbol if present.",
                "Identify medications, dosages, and frequencies in this discharge summary (example).",
                "Parse this résumé into structured fields: education[], experience[], skills[].",
                "List the three main experimental findings stated explicitly in this abstract.",
                "Build a table of URLs and anchor text from this HTML snippet.",
                "Extract named entities—people, orgs, locations—from this news clip.",
                "Pull action items from this meeting transcript with owner if stated.",
                "Return only CSV rows where status is overdue and sum the amount column.",
                "List every cited paper title and year from this bibliography block.",
                "Extract constraints from this brief: budget, deadline, must-haves, out-of-scope.",
                "Return structured fields: clause and penalty from this policy section.",
                "Convert this messy block into JSON with keys for each entity type you find.",
            ],
            keywords=[
                "extract",
                "pull out",
                "pull",
                "identify",
                "list all",
                "enumerate",
                "entities",
                "named entity",
                "fields",
                "structured",
                "json",
                "csv",
                "schema",
                "parse",
                "capture",
                "key findings",
                "line items",
                "slot",
                "annotation",
            ],
            patterns=[
                r"\bextract\b",
                r"\bpull out\b",
                r"\bkey findings\b",
                r"\bconvert to json\b",
                r"\b(?:as|into|to) (json|csv|yaml)\b",
                r"\bnamed entities\b|\bnamed entity\b",
                r"\bline items\b",
                r"\bstructured fields\b",
                r"\blist all\b",
            ],
            intent_verbs=[
                "extract",
                "identify",
                "list",
                "parse",
                "enumerate",
                "pull out",
            ],
            phrase_boosts=[
                "extract all",
                "pull out",
                "key findings",
                "structured fields",
                "convert to json",
                "list all entities",
                "named entities",
                "line items",
                "capture all",
                "parse into fields",
            ],
        ),
        "creative_writing": DomainDefinition(
            name="creative_writing",
            anchors=[
                "Write a 600-word noir short story about a museum guard who hears footsteps after closing.",
                "Draft a sonnet about migratory birds with slant rhyme and a volta in line 9.",
                "Compose dialogue between two siblings negotiating a haunted heirloom.",
                "World-build three factions on a tidally locked planet with conflicting resource ethics.",
                "Turn this logline into a three-act beat sheet for a contained thriller.",
                "Write a cold-open for a sitcom pilot in a chaotic community garden with a running gag.",
                "Pen lyrics for a folk song about winter train travel in iambic verse.",
                "Describe a surreal marketplace where memories are bartered; sensory detail over plot.",
                "Create voice sheets for an optimistic engineer and a cynical botanist on expedition.",
                "Write epistolary microfiction as increasingly unhinged summer postcards.",
                "Sketch dinner-table subtext-only conflict with no explicit insults.",
                "Generate a myth explaining why the moon flickers in this fantasy culture.",
                "Outline a children’s fable about patience with a non-cliché tortoise.",
                "Write microfiction under 100 words about the last bookstore on Earth.",
            ],
            keywords=[
                "story",
                "poem",
                "fiction",
                "novel",
                "scene",
                "dialogue",
                "character",
                "plot",
                "screenplay",
                "lyrics",
                "world-building",
                "fantasy",
                "horror",
                "monologue",
                "narrative",
                "prose",
                "stanza",
                "fable",
                "myth",
                "tone",
                "voice",
            ],
            patterns=[
                r"\b(write|pen|draft)\b.*\b(stor(y|ies)|novella|poem|screenplay)\b",
                r"\bworld-?build",
                r"\bcharacter arcs?\b",
                r"\bsonnet\b|\bhaiku\b",
                r"\bflash fiction\b|\bmicrofiction\b",
                r"\bhorror story\b|\bfantasy world\b",
            ],
            intent_verbs=[
                "write",
                "compose",
                "draft",
                "imagine",
                "invent",
                "narrate",
                "create",
            ],
            phrase_boosts=[
                "write a story",
                "write a poem",
                "fictional character",
                "dramatic monologue",
                "horror story",
                "fantasy world",
                "flash fiction",
                "world building",
                "plot twist",
                "in the style of",
            ],
        ),
        "factual_qa": DomainDefinition(
            name="factual_qa",
            anchors=[
                "What is photosynthesis, and what are the main inputs and outputs?",
                "Define polymorphism in object-oriented programming with one short Java-like example.",
                "Explain how vaccines train the adaptive immune system in plain language.",
                "How does HTTPS differ from HTTP for a nontechnical reader?",
                "What does quorum mean in distributed systems, and why does it matter?",
                "Teach the water cycle step by step for a middle school worksheet.",
                "How do transformers use self-attention—intuition only, no equations?",
                "What is the capital of Mongolia, and which languages are commonly spoken there?",
                "Describe buoyancy to a curious ten-year-old without formulas.",
                "What is CRISPR, and which genetics problems was it meant to address?",
                "Who was Ada Lovelace, and why is she significant in computing history?",
                "What is inflation, and how do central banks typically respond?",
                "Explain the pickleball kitchen-line rule and basic scoring for beginners.",
                "What is Big-O notation, and why do interviewers use it when discussing algorithms?",
            ],
            keywords=[
                "what is",
                "define",
                "definition",
                "explain",
                "describe",
                "how does",
                "how do",
                "meaning of",
                "tell me about",
                "teach",
                "tutorial",
                "introduction",
                "basics",
                "fundamentals",
                "concept",
                "elaborate",
                "for beginners",
                "in simple terms",
                "background",
                "overview",
            ],
            patterns=[
                r"\bwhat (is|are)\b",
                r"\bdefine\b",
                r"\bhow does\b.{0,80}\bwork\b",
                r"\btell me about\b",
                r"\bcan you explain\b",
                r"\bfor dummies\b|\beli5\b",
            ],
            intent_verbs=[
                "explain",
                "define",
                "describe",
                "teach",
                "clarify",
                "elaborate",
            ],
            phrase_boosts=[
                "what is",
                "explain what",
                "define",
                "how does this work",
                "explain in simple terms",
                "tell me about",
                "for beginners",
                "in plain language",
                "meaning of",
                "can you explain",
            ],
        ),
        "transformation": DomainDefinition(
            name="transformation",
            anchors=[
                "Rewrite this customer complaint reply to sound calm, empathetic, and policy-safe.",
                "Paraphrase this paragraph to avoid plagiarism while preserving technical meaning.",
                "Convert these bullets into a polished status email for stakeholders.",
                "Turn this passive-voice lab excerpt into concise active voice.",
                "Simplify this legal clause for a general audience without new commitments.",
                "Translate this casual update into formal British English for a board note.",
                "Reformat this recipe into numbered steps plus a grocery list section.",
                "Change the tone from sarcastic to sincere while preserving idea order.",
                "Expand this one-liner into a polite LinkedIn outreach under 120 words.",
                "Condense this pitch into a 50-word cold email hook with CTA.",
                "Convert this CSV to a Markdown table with aligned columns.",
                "Rewrite this SQL comment block into a short design note for reviewers.",
                "Polish this README so it reads professionally without adding fake benchmarks.",
                "Make this paragraph more concise while keeping all factual claims.",
            ],
            keywords=[
                "rewrite",
                "rephrase",
                "paraphrase",
                "reword",
                "convert",
                "translate",
                "reformat",
                "transform",
                "change tone",
                "tone shift",
                "simplify",
                "plain language",
                "formalize",
                "professional tone",
                "polish",
                "edit",
                "restyle",
                "sanitize",
            ],
            patterns=[
                r"\brewrite\b",
                r"\bparaphrase\b",
                r"\brephrase\b",
                r"\bpolish\b",
                r"\bturn this into\b",
                r"\bconvert\b.*\b(to|into)\b",
                r"\bchange (the )?tone\b",
                r"\b(in|to) (a )?more (professional|formal|casual)\b",
                r"\bsimplify this\b",
                r"\bconvert into bullet\b",
            ],
            intent_verbs=[
                "rewrite",
                "paraphrase",
                "rephrase",
                "convert",
                "simplify",
                "reformat",
                "translate",
                "polish",
            ],
            phrase_boosts=[
                "rewrite this",
                "paraphrase this",
                "professional tone",
                "simplify this",
                "convert into bullet points",
                "make this concise",
                "change the tone",
                "in formal language",
                "plain english",
                "more professional",
            ],
        ),
    }


DOMAIN_REGISTRY: Dict[str, DomainDefinition] = _domains()


def validate_registry() -> None:
    """Ensure registry matches supported domain list exactly."""
    missing = set(DOMAIN_NAMES) - set(DOMAIN_REGISTRY.keys())
    extra = set(DOMAIN_REGISTRY.keys()) - set(DOMAIN_NAMES)
    if missing or extra:
        raise RuntimeError(f"Domain registry mismatch. Missing: {missing}, Extra: {extra}")
    for name in DOMAIN_NAMES:
        d = DOMAIN_REGISTRY[name]
        if not (12 <= len(d.anchors) <= 15):
            raise RuntimeError(f"Domain {name} should have 12–15 anchors, got {len(d.anchors)}")
        if len(d.keywords) < 8:
            raise RuntimeError(f"Domain {name} needs realistic keyword coverage")
        if len(d.phrase_boosts) < 8:
            raise RuntimeError(f"Domain {name} needs phrase_boosts coverage (>=8)")


validate_registry()
